//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestClient.AVBusinessLayerReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AVBusinessLayerReference.IAVBusinessLayer")]
    public interface IAVBusinessLayer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAVBusinessLayer/DoWork", ReplyAction="http://tempuri.org/IAVBusinessLayer/DoWorkResponse")]
        string DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAVBusinessLayer/DoWork", ReplyAction="http://tempuri.org/IAVBusinessLayer/DoWorkResponse")]
        System.Threading.Tasks.Task<string> DoWorkAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAVBusinessLayerChannel : TestClient.AVBusinessLayerReference.IAVBusinessLayer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AVBusinessLayerClient : System.ServiceModel.ClientBase<TestClient.AVBusinessLayerReference.IAVBusinessLayer>, TestClient.AVBusinessLayerReference.IAVBusinessLayer {
        
        public AVBusinessLayerClient() {
        }
        
        public AVBusinessLayerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AVBusinessLayerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AVBusinessLayerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AVBusinessLayerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string DoWork() {
            return base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task<string> DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
    }
}
